export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SAVE_USER = 'SAVE_USER';
export const GET_TOKEN = 'GET_TOKEN';

export const GET_PAYEMENT_PAGE = 'GET_PAYEMENT_PAGE';
export const SET_PAYEMENT_LINK = 'SET_PAYEMENT_LINK';

export const GET_CALCULATE_START = 'GET_CALCULATE_START';
export const GET_CALCULATE_SUCCESS = 'GET_CALCULATE_SUCCESS';
export const GET_CALCULATE_FAIL = 'GET_CALCULATE_FAIL';
export const GET_CALCULATE = 'GET_CALCULATE';
export const MAKE_CALCULATION_START = 'MAKE_CALCULATION_START';
export const MAKE_CALCULATION_SUCCESS = 'MAKE_CALCULATION_SUCCESS';
export const MAKE_CALCULATION_FAIL = 'MAKE_CALCULATION_FAIL';
export const MAKE_CALCULATION = 'MAKE_CALCULATION';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
